---
title: Vond je het leuk?
hero_image: images/banner.png
description: Maak een machine learning-model dat op basis van je opmerkingen bepaalt of je een film of boek leuk vond.
version: 4
listed: true
copyedit: false
last_tested: '2024-06-19'
steps:
  - title: Wat ga je maken
  - title: Het project opzetten
  - title: Voorbeeld opmerkingen
    completion:
      - engaged
  - title: Train het model
  - title: Maak een emoji
  - title: Toon een reactie
    completion:
      - internal
  - title: 'Uitdaging'
    challenge: true
    completion:
      - external
