---
title: Vond je het leuk?
hero_image: images/banner.png
description: Maak een machine learning-model dat op basis van je opmerkingen bepaalt of je een film of boek leuk vond.
version: 4
listed: true
copyedit: false
last_tested: '2024-06-19'
steps:
  - 
    title: What you will make
  - 
    title: Set up the project
  - 
    title: Example comments
    completion:
      - engaged
  - 
    title: Train the model
  - 
    title: Create an emoji
  - 
    title: Show a reaction
    completion:
      - internal
  - 
    title: 'Challenge'
    challenge: true
  - 
    title: What can you do now?
    completion:
      - external
