---
title: Did you like it?
hero_image: images/banner.png
description: Create a machine learning model that will determine whether you liked
  a movie or book based on your comments.
version: 4
listed: false
copyedit: false
last_tested: '2024-06-19'
steps:
- title: Introduction
- title: Create a project and sprite costumes
- title: Collect examples for training
  completion:
  - engaged
- title: Train and test your machine learning model
- title: Use your machine learning model in Scratch
  completion:
  - internal
- title: 'Challenge: more characters and emotions'
  challenge: true
- title: What next?
