---
title: Gostaste?
hero_image: images/banner.png
description: Cria um modelo de machine learning que irá determinar se gostas-te de um filme ou livro com base nos teus comentários.
version: 4
listed: true
copyedit: false
last_tested: '2024-06-19'
steps:
  - 
    title: O que vais fazer
  - 
    title: Prepara o teu projeto
  - 
    title: Exemplos de comentários
    completion:
      - engaged
  - 
    title: Treina o modelo
  - 
    title: Cria um emoji
  - 
    title: Mostrar uma reação
    completion:
      - internal
  - 
    title: 'Desafio'
    challenge: true
    completion:
      - external
